biom/basic/models/Product.php
<?php

namespace app\models;

use Yii;
use yz\shoppingcart\CartPositionInterface;
use yz\shoppingcart\CartPositionTrait;

/**
 * This is the model class for table "product".
 *
 * @property integer $id
 * @property integer $category
 * @property integer $sub_category
 * @property string $title
 * @property integer $price
 * @property string $desc
 * @property string $image
 *
 * @property ProductImages $id0
 */
class Product extends \yii\db\ActiveRecord implements CartPositionInterface
{
    use CartPositionTrait;

     public function getPrice()
    {
        return $this->price;
    }

    public function getId()
    {
        return $this->id;
    }

    public $imageFiles;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category', 'title', 'price', 'desc'], 'required'],
            [['category', 'sub_category', 'price'], 'integer'],
            [['title'], 'string', 'max' => 110],
            [['desc'], 'string', 'max' => 500],
            [['image'], 'default'],
            [['imageFiles'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, jpeg', 'maxFiles' => 4],
        ];
    }





    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            
            foreach ($this->imageFiles as $file) {
                $names[] = $file->baseName . '.' . $file->extension;
            }
            
            $this->image = implode(';', $names);

            return true;
        } else {
            return false;
        }
    }    

    public function afterSave($insert, $changedAttributes)
    {
         $folder = Yii::getAlias('@webroot/uploads/').'/product/'.$this->id.'/';
            if (is_dir($folder) == false)
            mkdir($folder, 0777, true);
         
        foreach ($this->imageFiles as $file) {
            $file->saveAs($folder . $file->baseName . '.' . $file->extension);
        }

    }

    public function getImage(){
        return '<img src="uploads/product/'.$this->id.'/'.$this->image.'" />';
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category' => 'Категория',
            'sub_category' => 'Подкатегрия',
            'title' => 'Название',
            'price' => 'Цена',
            'desc' => 'Описание',
            'image' => 'Изображение',
        ];
    }


}

biom/basic/controllers/OrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Order;
use app\models\Product;
use app\models\searchOrder;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new searchOrder();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }    

    public function actionBasket()
    {
        $searchModel = new searchOrder();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('basket', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionOverView($id)
    {
        return $this->render('overview', [
            'model' => $this->findModel($id),
        ]);
    }    

    public function actionView($id)
    {
        $model = $this->findModel($id);
        $items = $this->getItems($model->items);

        return $this->render('view', [
            'model' => $model,
            'items' => $items,
        ]);
    }

    public function getItems($ids){
        $datas = explode(';', $ids);
        $items = [];
        foreach ($datas as $data) {
            $item = [];
            $keys = explode('-', $data);
            $model = Product::find()->where(['id' => $keys[0]])->one();
            $item['id'] = $model->id;
            $item['title'] = $model->title;
            $item['price'] = $model->price;
            $item['image'] = $model->image;
            $item['quantity'] = $keys[1];
            $items[]  = $item;
        }
        return $items;
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if( !\Yii::$app->user->isGuest ){
            $profile = \Yii::$app->user->identity->profile;
            $model->user_id = \Yii::$app->user->identity->id;
            $model->customers_firstname = $profile->name;
            $model->customers_lastname = $profile->last_name;
            $model->customers_email = $profile->public_email;
            $model->customers_contact_phone = $profile->contact_phone;
            $model->customers_mobile_phone = $profile->mobile_phone;
            $model->order_city = $profile->city;
            $model->order_street = $profile->street;
            $model->order_house = $profile->house;
            $model->order_apartment = $profile->apartament;
            $model->order_location = $profile->location;
        }

        $model->items= $this->setItems(\Yii::$app->request->get('id'), \Yii::$app->request->get('amount') );
        $model->due_amount = $this->setPrice(\Yii::$app->request->get('id'), \Yii::$app->request->get('amount') );

        if( \Yii::$app->request->get('delivery') ){
            $model->delivery_method = \Yii::$app->request->get('delivery');
        }          

    

        if( \Yii::$app->request->get('payment') ){
            $model->payment_method = \Yii::$app->request->get('payment');
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['overview', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function setPrice($id, $amount = 1){
        if($id){
            $model = Product::findOne($id);
            return $model->price * $amount;    
        } else {
            return \Yii::$app->cart->getCost();
        }
    }    

    public function setItems($id, $amount = 1){
        if($id){
            return \Yii::$app->request->get('id').'-'.$amount;   
        } else {
            $items = [];
            foreach(\Yii::$app->cart->positions as $position){
                $items[] = $position->id.'-'.$position->quantity;
            }
            return implode(';', $items);
        }
    }



    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }    

    public function actionOrders()
    {
        if(\Yii::$app->user->isGuest){
            $this->goBack();
        }
        
        $query = Order::find()->where([
            'user_id' => \Yii::$app->user->identity->getId(),
        ]); 

        $dataProvider = new \yii\data\ActiveDataProvider([
          'query'=>$query,
        ]);

        return $this->render('orders', [
                'dataProvider'=>$dataProvider,
        ]);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

biom/basic/controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\Product;
use yii\data\ActiveDataProvider;
use yz\shoppingcart\ShoppingCart;

class ProductController extends \yii\web\Controller
{
    public function actionIndex()
    {
    	if (\Yii::$app->request->isAjax) {
    		$cart = new ShoppingCart();
    		$model = Product::findOne(\Yii::$app->request->get('id'));

    		if ($model) {
	        	\Yii::$app->cart->put($model, \Yii::$app->request->get('amount'));

                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                $items = ['items' => $this->renderPartial('cart_block'), 'total' => \Yii::$app->cart->getCost()];
                return $items;
	    	}
 
	    	return 'wa';
    	}
        $searchModel = new Product();
        $parameters = \Yii::$app->request->queryParams;
		unset($parameters['r']);

		$query = Product::find()->where($parameters);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionRemove()
	{
        $cart = new ShoppingCart();
        $model = Product::findOne(\Yii::$app->request->get('id'));

        if ($model) {
            \Yii::$app->cart->remove($model);
            return \Yii::$app->cart->getCost();
        }
	}

}

biom/basic/views/product/_cart_item.php
<?php
	use yii\helpers\Html;
	use yii\helpers\Url;
?>                      <div class="item" data="<?= $position->id; ?>">
                            <div class="leftpart">
                                <p class="title rp"><?= $position->title; ?></p>
                                <p class="price rp"><?= $position->quantity?>кг / <?= $position->price ?> тг</p>
                            </div>
                            <?= Html::a('<img src="img/cross.jpg">', Url::toRoute('product/remove'), ['class'=>'cross', 'data-id'=> $position->id] ); ?>
                            <div class="clearfix"></div>
                        </div> 

biom/basic/views/product/_item.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\touchspin\TouchSpin;
?>


<div class="prod-single">
    <div class="leftpart">
        <img src="uploads/product/<?= $model->id; ?>/<?= $model->image; ?>">
    </div>
    <div class="rightpart">
        <p class="title rp"><?= $model->title; ?></p>
        <p class="price rp"><?= $model->price; ?> тг/кг</p>
        <p class="amount rp">Какое кол-во желаете?</p>
        <form class="basketForm" data-id="<?= $model->id; ?>">
            <input type="number" min="1" max="30" name="amount" value="1" />
            <input type="hidden" value="<?= $model->id; ?>" name="id">
            <div class="button-wrap">
                <button class="waves-effect waves-green btn rp" type="submit">В корзину</button>
            </div>
            <div class="button-wrap">   
                <a href="#" data-id="<?= $model->id; ?>" class="waves-effect waves-green btn rp ">Оформить заказ</a>
            </div> 
        </form>

    <?php $form = ActiveForm::begin([
        'method'=>'GET',
        'action'=>Url::toRoute('order/create'),
        'options'=>['class'=>'create-order-form', 'id'=>"form-".$model->id]
    ]); ?> 
            <input type="number" min="1" max="30" name="amount" value="1" />
            <input type="hidden" value="<?= $model->id; ?>" name="id">
    <?php ActiveForm::end(); ?>


    </div>
    <div class="bottom-part">
        <div class="left"></div>
        <div class="right">
            <p class="desc"><?= $model->desc; ?></p> 
        </div>
    </div>
</div>

biom/basic/views/product/cart_block.php
                  
                    <?php
                            /** @var ShoppingCart $sc */
                            foreach(\Yii::$app->cart->positions as $position){
                              echo $this->render('_cart_item',['position'=>$position]);
                              //var_dump($position);
                            }
                    ?>

biom/basic/views/product/index.php
<?php
    use yii\widgets\ListView;
    use yii\helpers\Html;
    use yii\helpers\Url;
    use yii\widgets\ActiveForm;
?> 
        <div class="prod-part">
            <div class="head">
                <img src="img/prod-icon1.png">
                <div class="info">
                    <p class="sub-category rp">Говядина</p>
                    <p class="category rp">Мясная продукция</p>
                </div>
            <div class="main-head">
            <?php if (!\Yii::$app->user->isGuest)  :?>
                <?= Html::a('Профиль', Url::toRoute('user/settings/profile'))?>
                <?= Html::a('Выйти', Url::toRoute('user/security/logout'), ['data-method' => 'post'])?>                
            <?php else : ?>
                <a href="#log_modal" class="modal-trigger">Войти</a>
                <a href="#reg_modal" class="modal-trigger">Регистрация</a>
            <?php endif; ?>
            </div>
                <div class="arrows">
                    <div class="left">
                        &#9668;
                    </div>
                    <div class="right">
                        &#9658;
                    </div>                   
                    
                </div>
            </div>
            <div class="main-prod main-section">

                <section class="basket-block">
                    <div class="top">
                        <img src="img/basket-logo-small.png">
                        <span class="rp">Ваша корзина</span>
                    </div>
                    <div class="basket-list">   
                        <?= $this->render('cart_block'); ?>
                    </div>
                    <div class="bottom">
                        <p class="total rp">Итого на сумму</p>
                        <p class="price rp "><span class="total-amount"><?= \Yii::$app->cart->getCost(); ?></span> тг</p>
                        <p class="total rp">Способ доставки</p>
                            <?php $form = ActiveForm::begin([
                                'method'=>'get',
                                'action'=> Url::toRoute('order/create'),
                            ]); ?>
                             <div class="input-wrap">
                                <input type="radio" id="del_1" checked="true" name="delivery" value="1">
                                <label for="del_1" class="rp" >City 1000</label>    
                            </div>                            
                            <div class="input-wrap">
                                <input type="radio" id="del_2" name="delivery" value="2">
                                <label for="del_2" class="rp">Express</label>   
                            </div>       
                <?= Html::submitButton('Оформить заказ', ['class' => 'm_button rp']) ?>                


    <?php ActiveForm::end(); ?>

                        
                    </div>
                </section>

                <?= ListView::widget( [
                        'layout'=>'{items}',
                        'dataProvider' => $dataProvider,
                        'itemView' => '_item',
                     ] ); 
                ?>

               

        </div>