biom/basic/controllers/OrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Order;
use app\models\Product;
use app\models\searchOrder;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new searchOrder();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }    

    public function actionBasket()
    {
        $searchModel = new searchOrder();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('basket', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionOverView($id)
    {
        return $this->render('overview', [
            'model' => $this->findModel($id),
        ]);
    }    

    public function actionView($id)
    {
        $model = $this->findModel($id);
        $items = $this->getItems($model->items);

        return $this->render('view', [
            'model' => $model,
            'items' => $items,
        ]);
    }

    public function getItems($ids){
        $datas = explode(';', $ids);
        $items = [];
        foreach ($datas as $data) {
            $item = [];
            $keys = explode('-', $data);
            $model = Product::find()->where(['id' => $keys[0]])->one();
            $item['id'] = $model->id;
            $item['title'] = $model->title;
            $item['price'] = $model->price;
            $item['image'] = $model->image;
            $item['quantity'] = $keys[1];
            $items[]  = $item;
        }
        return $items;
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if( !\Yii::$app->user->isGuest ){
            $profile = \Yii::$app->user->identity->profile;
            $model->user_id = \Yii::$app->user->identity->id;
            $model->customers_firstname = $profile->name;
            $model->customers_lastname = $profile->last_name;
            $model->customers_email = $profile->public_email;
            $model->customers_contact_phone = $profile->contact_phone;
            $model->customers_mobile_phone = $profile->mobile_phone;
            $model->order_city = $profile->city;
            $model->order_street = $profile->street;
            $model->order_house = $profile->house;
            $model->order_apartment = $profile->apartament;
            $model->order_location = $profile->location;
        }

        $model->items= $this->setItems(\Yii::$app->request->get('id'), \Yii::$app->request->get('amount') );
        $model->due_amount = $this->setPrice(\Yii::$app->request->get('id'), \Yii::$app->request->get('amount') );

        if( \Yii::$app->request->get('delivery') ){
            $model->delivery_method = \Yii::$app->request->get('delivery');
        }          

    

        if( \Yii::$app->request->get('payment') ){
            $model->payment_method = \Yii::$app->request->get('payment');
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['overview', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function setPrice($id, $amount = 1){
        if($id){
            $model = Product::findOne($id);
            return $model->price * $amount;    
        } else {
            return \Yii::$app->cart->getCost();
        }
    }    

    public function setItems($id, $amount = 1){
        if($id){
            return \Yii::$app->request->get('id').'-'.$amount;   
        } else {
            $items = [];
            foreach(\Yii::$app->cart->positions as $position){
                $items[] = $position->id.'-'.$position->quantity;
            }
            return implode(';', $items);
        }
    }



    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }    

    public function actionOrders()
    {
        if(\Yii::$app->user->isGuest){
            $this->goBack();
        }
        
        $query = Order::find()->where([
            'user_id' => \Yii::$app->user->identity->getId(),
        ]); 

        $dataProvider = new \yii\data\ActiveDataProvider([
          'query'=>$query,
        ]);

        return $this->render('orders', [
                'dataProvider'=>$dataProvider,
        ]);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

biom/basic/controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\Product;
use yii\data\ActiveDataProvider;
use yz\shoppingcart\ShoppingCart;

class ProductController extends \yii\web\Controller
{
    public function actionIndex()
    {
    	if (\Yii::$app->request->isAjax) {
    		$cart = new ShoppingCart();
    		$model = Product::findOne(\Yii::$app->request->get('id'));

    		if ($model) {
	        	\Yii::$app->cart->put($model, \Yii::$app->request->get('amount'));

                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                $items = ['items' => $this->renderPartial('cart_block'), 'total' => \Yii::$app->cart->getCost()];
                return $items;
	    	}
 
	    	return 'wa';
    	}
        $searchModel = new Product();
        $parameters = \Yii::$app->request->queryParams;
		unset($parameters['r']);

		$query = Product::find()->where($parameters);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionRemove()
	{
        $cart = new ShoppingCart();
        $model = Product::findOne(\Yii::$app->request->get('id'));

        if ($model) {
            \Yii::$app->cart->remove($model);
            return \Yii::$app->cart->getCost();
        }
	}

}

biom/basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav; 
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<?php if (Yii::$app->user->isGuest): ?>

<?= $this->render('registerForm'); ?>

<?php endif;?>

        <?= $this->render('menu'); ?>


         <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

biom/basic/views/layouts/menu.php
<?php
    use yii\helpers\Html;
    use yii\helpers\Url;
?>
        <nav>
            <?= Html::a('<img src="img/main-logo.jpg">', ['/']); ?> 
            <a href="#"></a>
            <div class="sub-menu">
                <div class="menu" id="main">
                    <p class="title rp">Общее меню</p>
                    <ul>
                        <li><a href="#" class="rp">- О проекте</a></li>
                        <li><a href="#" class="rp">- Доставка и оплата</a></li>
                        <li><a href="#" class="rp">- Как сделать заказ</a></li>
                        <li><a href="#" class="rp">- Вопрос-ответ</a></li>
                        <li><a href="#" class="rp">- Как нас найти</a></li>
                    </ul>
                </div>                
                <div class="menu" id="meat">
                    <p class="title rp">Мясная продукция</p>
                    <ul>
                        <li> <?= Html::a('- Говядина', ['/product/index', 'category'=>1, 'sub_category'=>1], ['class'=>'rp']) ?> </li>
                        <li><?= Html::a('- Баранина', ['/product/index', 'category'=>1, 'sub_category'=>2], ['class'=>'rp']) ?> </li>
                        <li><?= Html::a('- Конина', ['/product/index', 'category'=>1, 'sub_category'=>3], ['class'=>'rp']) ?> </li>
                        <li><a href="#" class="ep">- Свинина</a></li>
                    </ul>
                </div>                
                <div class="menu" id="fish">
                    <p class="title rp">Рыбная продукция</p>
                    <ul>
                        <li><a href="#" class="rp">- Лещ</a></li>
                        <li><a href="#" class="rp">- Форель</a></li>
                        <li><a href="#" class="rp">- Угорь</a></li>
                        <li><a href="#" class="rp">- Селедка</a></li>
                    </ul>
                </div>
            </div>
            <ul class="main-menu">
                <li class="submenu" menu="main">
                    <a href="#" class="main-menu">Меню</a>
                </li>
                <li class="nomenu">
                    <?= Html::a('', Url::toRoute('/order/basket'), ['id'=>'basketButton'])?>
                </li>
                <li class="submenu" menu="meat"></li>
                <li class="submenu" menu="fish"></li>
                <li class="nomenu"></li>
                <li class="nomenu"></li>
                <li class="nomenu"></li>
                <li class="nomenu"></li>
            </ul>

            <p class="copyright">
                <span>&copy; 2015</span> bio-m.kz <br/>
                <span>Разработка</span> <a href="http://dynamica.kz">Dynamica</a>
            </p>
        </nav>

biom/basic/views/layouts/registerForm.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dektrium\user\models\RegistrationForm;
use dektrium\user\models\LoginForm;
use yii\helpers\Url;

/**
 * @var yii\web\View              $this
 * @var dektrium\user\models\User $user
 * @var dektrium\user\Module      $module
 */
$model = \Yii::createObject(RegistrationForm::className());
$modelLog = \Yii::createObject(LoginForm::className());
?>

<?php if(\Yii::$app->user->isGuest ) :?>

        <div id="reg_modal" class="modal user-modal">
           <div class="main-frame">
                <img src="img/logo-small.png">
                <p class="rp">Регистрация</p>
                <?php $form = ActiveForm::begin([
                    'id'                     => 'registration-form',
                    'enableAjaxValidation'   => true,
                    'enableClientValidation' => false,
                    'action' => Url::toRoute('user/registration/register'),
                    'options'=>['autocomplete'=>'off'],
                ]); ?>
                    <?= $form->field($model, 'email')->textInput(['autocomplete'=>'off', 'placeholder'=>'Ваш email', ])->label(false); ?>
                    <?= $form->field($model, 'password')->passwordInput(['autocomplete'=>'off', 'placeholder'=>'Пароль'])->label(false); ?>
                    <?= $form->field($model, 'agree', ['template'=>'{input}<label for="register-form-agree" class="rp">Согласен с <a href="">Правилами ресурса</a></label>'])->checkBox(['label' => null]); ?>
                    <?= Html::submitButton('Зарегистрировать', ['class' => 'waves-effect waves-green btn rp']) ?>
                <?php ActiveForm::end(); ?>
           </div>
        </div>        

        <div id="log_modal" class="modal user-modal">
           <div class="main-frame">
                <img src="img/logo-small.png">
                <p class="rp">Вход в профиль</p>
                <?php $form = ActiveForm::begin([
                    'id'                     => 'login-form',
                    'enableAjaxValidation'   => true,
                    'enableClientValidation' => false,
                    'validateOnBlur'         => false,
                    'validateOnType'         => false,
                    'validateOnChange'       => false,
                    'action' => Url::toRoute('user/security/login'),
                ]); ?>
                <?= $form->errorSummary($model); ?>
                    <?= $form->field($modelLog, 'login', ['inputOptions' => ['autofocus' => 'autofocus', 'class' => 'form-control', 'tabindex' => '1']])->label(false); ?>
                    <?= $form->field($modelLog, 'password', ['inputOptions' => ['class' => 'form-control', 'tabindex' => '2']])->passwordInput()->label(false); ?>
                    <?= $form->field($modelLog, 'rememberMe', ['template'=>'{input}<label for="login-form-rememberme" class="rp">Запомнить</label>'])->checkBox(['tabindex' => '4', 'label' => null]); ?>
                    <?= Html::submitButton('Войти', ['class' => 'waves-effect waves-green btn rp', 'tabindex' => '3']) ?>
                <?php ActiveForm::end(); ?>
           </div>
        </div>
<?php endif; ?>



